//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketClient.LoginService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OturumResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OturumResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoginService.LoginServiceSoap")]
    public interface LoginServiceSoap {
        
        // CODEGEN: Generating message contract since element name oturum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGiris", ReplyAction="*")]
        SirketClient.LoginService.MusteriGirisResponse MusteriGiris(SirketClient.LoginService.MusteriGirisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriGiris", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.LoginService.MusteriGirisResponse> MusteriGirisAsync(SirketClient.LoginService.MusteriGirisRequest request);
        
        // CODEGEN: Generating message contract since element name oturum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KurumsalGiris", ReplyAction="*")]
        SirketClient.LoginService.KurumsalGirisResponse KurumsalGiris(SirketClient.LoginService.KurumsalGirisRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KurumsalGiris", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.LoginService.KurumsalGirisResponse> KurumsalGirisAsync(SirketClient.LoginService.KurumsalGirisRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGirisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGiris", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.LoginService.MusteriGirisRequestBody Body;
        
        public MusteriGirisRequest() {
        }
        
        public MusteriGirisRequest(SirketClient.LoginService.MusteriGirisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriGirisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.LoginService.OturumResult oturum;
        
        public MusteriGirisRequestBody() {
        }
        
        public MusteriGirisRequestBody(SirketClient.LoginService.OturumResult oturum) {
            this.oturum = oturum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriGirisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriGirisResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.LoginService.MusteriGirisResponseBody Body;
        
        public MusteriGirisResponse() {
        }
        
        public MusteriGirisResponse(SirketClient.LoginService.MusteriGirisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriGirisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MusteriGirisResult;
        
        public MusteriGirisResponseBody() {
        }
        
        public MusteriGirisResponseBody(bool MusteriGirisResult) {
            this.MusteriGirisResult = MusteriGirisResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KurumsalGirisRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KurumsalGiris", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.LoginService.KurumsalGirisRequestBody Body;
        
        public KurumsalGirisRequest() {
        }
        
        public KurumsalGirisRequest(SirketClient.LoginService.KurumsalGirisRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KurumsalGirisRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.LoginService.OturumResult oturum;
        
        public KurumsalGirisRequestBody() {
        }
        
        public KurumsalGirisRequestBody(SirketClient.LoginService.OturumResult oturum) {
            this.oturum = oturum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KurumsalGirisResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KurumsalGirisResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.LoginService.KurumsalGirisResponseBody Body;
        
        public KurumsalGirisResponse() {
        }
        
        public KurumsalGirisResponse(SirketClient.LoginService.KurumsalGirisResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KurumsalGirisResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool KurumsalGirisResult;
        
        public KurumsalGirisResponseBody() {
        }
        
        public KurumsalGirisResponseBody(bool KurumsalGirisResult) {
            this.KurumsalGirisResult = KurumsalGirisResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoginServiceSoapChannel : SirketClient.LoginService.LoginServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginServiceSoapClient : System.ServiceModel.ClientBase<SirketClient.LoginService.LoginServiceSoap>, SirketClient.LoginService.LoginServiceSoap {
        
        public LoginServiceSoapClient() {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoginServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.LoginService.MusteriGirisResponse SirketClient.LoginService.LoginServiceSoap.MusteriGiris(SirketClient.LoginService.MusteriGirisRequest request) {
            return base.Channel.MusteriGiris(request);
        }
        
        public bool MusteriGiris(SirketClient.LoginService.OturumResult oturum) {
            SirketClient.LoginService.MusteriGirisRequest inValue = new SirketClient.LoginService.MusteriGirisRequest();
            inValue.Body = new SirketClient.LoginService.MusteriGirisRequestBody();
            inValue.Body.oturum = oturum;
            SirketClient.LoginService.MusteriGirisResponse retVal = ((SirketClient.LoginService.LoginServiceSoap)(this)).MusteriGiris(inValue);
            return retVal.Body.MusteriGirisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.LoginService.MusteriGirisResponse> SirketClient.LoginService.LoginServiceSoap.MusteriGirisAsync(SirketClient.LoginService.MusteriGirisRequest request) {
            return base.Channel.MusteriGirisAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.LoginService.MusteriGirisResponse> MusteriGirisAsync(SirketClient.LoginService.OturumResult oturum) {
            SirketClient.LoginService.MusteriGirisRequest inValue = new SirketClient.LoginService.MusteriGirisRequest();
            inValue.Body = new SirketClient.LoginService.MusteriGirisRequestBody();
            inValue.Body.oturum = oturum;
            return ((SirketClient.LoginService.LoginServiceSoap)(this)).MusteriGirisAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.LoginService.KurumsalGirisResponse SirketClient.LoginService.LoginServiceSoap.KurumsalGiris(SirketClient.LoginService.KurumsalGirisRequest request) {
            return base.Channel.KurumsalGiris(request);
        }
        
        public bool KurumsalGiris(SirketClient.LoginService.OturumResult oturum) {
            SirketClient.LoginService.KurumsalGirisRequest inValue = new SirketClient.LoginService.KurumsalGirisRequest();
            inValue.Body = new SirketClient.LoginService.KurumsalGirisRequestBody();
            inValue.Body.oturum = oturum;
            SirketClient.LoginService.KurumsalGirisResponse retVal = ((SirketClient.LoginService.LoginServiceSoap)(this)).KurumsalGiris(inValue);
            return retVal.Body.KurumsalGirisResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.LoginService.KurumsalGirisResponse> SirketClient.LoginService.LoginServiceSoap.KurumsalGirisAsync(SirketClient.LoginService.KurumsalGirisRequest request) {
            return base.Channel.KurumsalGirisAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.LoginService.KurumsalGirisResponse> KurumsalGirisAsync(SirketClient.LoginService.OturumResult oturum) {
            SirketClient.LoginService.KurumsalGirisRequest inValue = new SirketClient.LoginService.KurumsalGirisRequest();
            inValue.Body = new SirketClient.LoginService.KurumsalGirisRequestBody();
            inValue.Body.oturum = oturum;
            return ((SirketClient.LoginService.LoginServiceSoap)(this)).KurumsalGirisAsync(inValue);
        }
    }
}
