//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketClient.MusteriService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusteriResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MusteriResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int MusteriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCkimlikField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MusteriID {
            get {
                return this.MusteriIDField;
            }
            set {
                if ((this.MusteriIDField.Equals(value) != true)) {
                    this.MusteriIDField = value;
                    this.RaisePropertyChanged("MusteriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Soyad {
            get {
                return this.SoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyadField, value) != true)) {
                    this.SoyadField = value;
                    this.RaisePropertyChanged("Soyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TCkimlik {
            get {
                return this.TCkimlikField;
            }
            set {
                if ((object.ReferenceEquals(this.TCkimlikField, value) != true)) {
                    this.TCkimlikField = value;
                    this.RaisePropertyChanged("TCkimlik");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OturumM", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class OturumM : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MusteriService.MusteriServiceSoap")]
    public interface MusteriServiceSoap {
        
        // CODEGEN: Generating message contract since element name musteri from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriEkle", ReplyAction="*")]
        SirketClient.MusteriService.MusteriEkleResponse MusteriEkle(SirketClient.MusteriService.MusteriEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.MusteriService.MusteriEkleResponse> MusteriEkleAsync(SirketClient.MusteriService.MusteriEkleRequest request);
        
        // CODEGEN: Generating message contract since element name oturum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OturumEkle", ReplyAction="*")]
        SirketClient.MusteriService.OturumEkleResponse OturumEkle(SirketClient.MusteriService.OturumEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OturumEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.MusteriService.OturumEkleResponse> OturumEkleAsync(SirketClient.MusteriService.OturumEkleRequest request);
        
        // CODEGEN: Generating message contract since element name MusteriListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriListele", ReplyAction="*")]
        SirketClient.MusteriService.MusteriListeleResponse MusteriListele(SirketClient.MusteriService.MusteriListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MusteriListele", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.MusteriService.MusteriListeleResponse> MusteriListeleAsync(SirketClient.MusteriService.MusteriListeleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriEkle", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.MusteriService.MusteriEkleRequestBody Body;
        
        public MusteriEkleRequest() {
        }
        
        public MusteriEkleRequest(SirketClient.MusteriService.MusteriEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.MusteriService.MusteriResult musteri;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public SirketClient.MusteriService.OturumM otr;
        
        public MusteriEkleRequestBody() {
        }
        
        public MusteriEkleRequestBody(SirketClient.MusteriService.MusteriResult musteri, SirketClient.MusteriService.OturumM otr) {
            this.musteri = musteri;
            this.otr = otr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.MusteriService.MusteriEkleResponseBody Body;
        
        public MusteriEkleResponse() {
        }
        
        public MusteriEkleResponse(SirketClient.MusteriService.MusteriEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MusteriEkleResponseBody {
        
        public MusteriEkleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OturumEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OturumEkle", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.MusteriService.OturumEkleRequestBody Body;
        
        public OturumEkleRequest() {
        }
        
        public OturumEkleRequest(SirketClient.MusteriService.OturumEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OturumEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.MusteriService.OturumM oturum;
        
        public OturumEkleRequestBody() {
        }
        
        public OturumEkleRequestBody(SirketClient.MusteriService.OturumM oturum) {
            this.oturum = oturum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OturumEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OturumEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.MusteriService.OturumEkleResponseBody Body;
        
        public OturumEkleResponse() {
        }
        
        public OturumEkleResponse(SirketClient.MusteriService.OturumEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class OturumEkleResponseBody {
        
        public OturumEkleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriListele", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.MusteriService.MusteriListeleRequestBody Body;
        
        public MusteriListeleRequest() {
        }
        
        public MusteriListeleRequest(SirketClient.MusteriService.MusteriListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MusteriListeleRequestBody {
        
        public MusteriListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MusteriListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MusteriListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.MusteriService.MusteriListeleResponseBody Body;
        
        public MusteriListeleResponse() {
        }
        
        public MusteriListeleResponse(SirketClient.MusteriService.MusteriListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MusteriListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.MusteriService.MusteriResult[] MusteriListeleResult;
        
        public MusteriListeleResponseBody() {
        }
        
        public MusteriListeleResponseBody(SirketClient.MusteriService.MusteriResult[] MusteriListeleResult) {
            this.MusteriListeleResult = MusteriListeleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MusteriServiceSoapChannel : SirketClient.MusteriService.MusteriServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MusteriServiceSoapClient : System.ServiceModel.ClientBase<SirketClient.MusteriService.MusteriServiceSoap>, SirketClient.MusteriService.MusteriServiceSoap {
        
        public MusteriServiceSoapClient() {
        }
        
        public MusteriServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MusteriServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusteriServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MusteriServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.MusteriService.MusteriEkleResponse SirketClient.MusteriService.MusteriServiceSoap.MusteriEkle(SirketClient.MusteriService.MusteriEkleRequest request) {
            return base.Channel.MusteriEkle(request);
        }
        
        public void MusteriEkle(SirketClient.MusteriService.MusteriResult musteri, SirketClient.MusteriService.OturumM otr) {
            SirketClient.MusteriService.MusteriEkleRequest inValue = new SirketClient.MusteriService.MusteriEkleRequest();
            inValue.Body = new SirketClient.MusteriService.MusteriEkleRequestBody();
            inValue.Body.musteri = musteri;
            inValue.Body.otr = otr;
            SirketClient.MusteriService.MusteriEkleResponse retVal = ((SirketClient.MusteriService.MusteriServiceSoap)(this)).MusteriEkle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.MusteriService.MusteriEkleResponse> SirketClient.MusteriService.MusteriServiceSoap.MusteriEkleAsync(SirketClient.MusteriService.MusteriEkleRequest request) {
            return base.Channel.MusteriEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.MusteriService.MusteriEkleResponse> MusteriEkleAsync(SirketClient.MusteriService.MusteriResult musteri, SirketClient.MusteriService.OturumM otr) {
            SirketClient.MusteriService.MusteriEkleRequest inValue = new SirketClient.MusteriService.MusteriEkleRequest();
            inValue.Body = new SirketClient.MusteriService.MusteriEkleRequestBody();
            inValue.Body.musteri = musteri;
            inValue.Body.otr = otr;
            return ((SirketClient.MusteriService.MusteriServiceSoap)(this)).MusteriEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.MusteriService.OturumEkleResponse SirketClient.MusteriService.MusteriServiceSoap.OturumEkle(SirketClient.MusteriService.OturumEkleRequest request) {
            return base.Channel.OturumEkle(request);
        }
        
        public void OturumEkle(SirketClient.MusteriService.OturumM oturum) {
            SirketClient.MusteriService.OturumEkleRequest inValue = new SirketClient.MusteriService.OturumEkleRequest();
            inValue.Body = new SirketClient.MusteriService.OturumEkleRequestBody();
            inValue.Body.oturum = oturum;
            SirketClient.MusteriService.OturumEkleResponse retVal = ((SirketClient.MusteriService.MusteriServiceSoap)(this)).OturumEkle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.MusteriService.OturumEkleResponse> SirketClient.MusteriService.MusteriServiceSoap.OturumEkleAsync(SirketClient.MusteriService.OturumEkleRequest request) {
            return base.Channel.OturumEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.MusteriService.OturumEkleResponse> OturumEkleAsync(SirketClient.MusteriService.OturumM oturum) {
            SirketClient.MusteriService.OturumEkleRequest inValue = new SirketClient.MusteriService.OturumEkleRequest();
            inValue.Body = new SirketClient.MusteriService.OturumEkleRequestBody();
            inValue.Body.oturum = oturum;
            return ((SirketClient.MusteriService.MusteriServiceSoap)(this)).OturumEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.MusteriService.MusteriListeleResponse SirketClient.MusteriService.MusteriServiceSoap.MusteriListele(SirketClient.MusteriService.MusteriListeleRequest request) {
            return base.Channel.MusteriListele(request);
        }
        
        public SirketClient.MusteriService.MusteriResult[] MusteriListele() {
            SirketClient.MusteriService.MusteriListeleRequest inValue = new SirketClient.MusteriService.MusteriListeleRequest();
            inValue.Body = new SirketClient.MusteriService.MusteriListeleRequestBody();
            SirketClient.MusteriService.MusteriListeleResponse retVal = ((SirketClient.MusteriService.MusteriServiceSoap)(this)).MusteriListele(inValue);
            return retVal.Body.MusteriListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.MusteriService.MusteriListeleResponse> SirketClient.MusteriService.MusteriServiceSoap.MusteriListeleAsync(SirketClient.MusteriService.MusteriListeleRequest request) {
            return base.Channel.MusteriListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.MusteriService.MusteriListeleResponse> MusteriListeleAsync() {
            SirketClient.MusteriService.MusteriListeleRequest inValue = new SirketClient.MusteriService.MusteriListeleRequest();
            inValue.Body = new SirketClient.MusteriService.MusteriListeleRequestBody();
            return ((SirketClient.MusteriService.MusteriServiceSoap)(this)).MusteriListeleAsync(inValue);
        }
    }
}
