//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirketClient.AracService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AracResult", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class AracResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AracIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        private System.Nullable<int> AracYasiField;
        
        private System.Nullable<int> BagajHacmiField;
        
        private System.Nullable<int> KoltukSayisiField;
        
        private System.Nullable<decimal> GunlukFiyatField;
        
        private System.Nullable<bool> KiralanmaDurumuField;
        
        private System.Nullable<bool> AirbagDurumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int AracID {
            get {
                return this.AracIDField;
            }
            set {
                if ((this.AracIDField.Equals(value) != true)) {
                    this.AracIDField = value;
                    this.RaisePropertyChanged("AracID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<int> AracYasi {
            get {
                return this.AracYasiField;
            }
            set {
                if ((this.AracYasiField.Equals(value) != true)) {
                    this.AracYasiField = value;
                    this.RaisePropertyChanged("AracYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<int> BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> GunlukFiyat {
            get {
                return this.GunlukFiyatField;
            }
            set {
                if ((this.GunlukFiyatField.Equals(value) != true)) {
                    this.GunlukFiyatField = value;
                    this.RaisePropertyChanged("GunlukFiyat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<bool> KiralanmaDurumu {
            get {
                return this.KiralanmaDurumuField;
            }
            set {
                if ((this.KiralanmaDurumuField.Equals(value) != true)) {
                    this.KiralanmaDurumuField = value;
                    this.RaisePropertyChanged("KiralanmaDurumu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<bool> AirbagDurum {
            get {
                return this.AirbagDurumField;
            }
            set {
                if ((this.AirbagDurumField.Equals(value) != true)) {
                    this.AirbagDurumField = value;
                    this.RaisePropertyChanged("AirbagDurum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracService.AracServiceSoap")]
    public interface AracServiceSoap {
        
        // CODEGEN: Generating message contract since element name arac from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YeniAracEkle", ReplyAction="*")]
        SirketClient.AracService.YeniAracEkleResponse YeniAracEkle(SirketClient.AracService.YeniAracEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YeniAracEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.AracService.YeniAracEkleResponse> YeniAracEkleAsync(SirketClient.AracService.YeniAracEkleRequest request);
        
        // CODEGEN: Generating message contract since element name KullaniciAdi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracListele", ReplyAction="*")]
        SirketClient.AracService.AracListeleResponse AracListele(SirketClient.AracService.AracListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracListele", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.AracService.AracListeleResponse> AracListeleAsync(SirketClient.AracService.AracListeleRequest request);
        
        // CODEGEN: Generating message contract since element name arac from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracGuncelle", ReplyAction="*")]
        SirketClient.AracService.AracGuncelleResponse AracGuncelle(SirketClient.AracService.AracGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<SirketClient.AracService.AracGuncelleResponse> AracGuncelleAsync(SirketClient.AracService.AracGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracSil", ReplyAction="*")]
        void AracSil(int aracID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AracSil", ReplyAction="*")]
        System.Threading.Tasks.Task AracSilAsync(int aracID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YeniAracEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YeniAracEkle", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.AracService.YeniAracEkleRequestBody Body;
        
        public YeniAracEkleRequest() {
        }
        
        public YeniAracEkleRequest(SirketClient.AracService.YeniAracEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class YeniAracEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.AracService.AracResult arac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KullaniciAdi;
        
        public YeniAracEkleRequestBody() {
        }
        
        public YeniAracEkleRequestBody(SirketClient.AracService.AracResult arac, string KullaniciAdi) {
            this.arac = arac;
            this.KullaniciAdi = KullaniciAdi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class YeniAracEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="YeniAracEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.AracService.YeniAracEkleResponseBody Body;
        
        public YeniAracEkleResponse() {
        }
        
        public YeniAracEkleResponse(SirketClient.AracService.YeniAracEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class YeniAracEkleResponseBody {
        
        public YeniAracEkleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracListele", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.AracService.AracListeleRequestBody Body;
        
        public AracListeleRequest() {
        }
        
        public AracListeleRequest(SirketClient.AracService.AracListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracListeleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string KullaniciAdi;
        
        public AracListeleRequestBody() {
        }
        
        public AracListeleRequestBody(string KullaniciAdi) {
            this.KullaniciAdi = KullaniciAdi;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.AracService.AracListeleResponseBody Body;
        
        public AracListeleResponse() {
        }
        
        public AracListeleResponse(SirketClient.AracService.AracListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<SirketClient.AracService.AracResult> AracListeleResult;
        
        public AracListeleResponseBody() {
        }
        
        public AracListeleResponseBody(System.Collections.Generic.List<SirketClient.AracService.AracResult> AracListeleResult) {
            this.AracListeleResult = AracListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.AracService.AracGuncelleRequestBody Body;
        
        public AracGuncelleRequest() {
        }
        
        public AracGuncelleRequest(SirketClient.AracService.AracGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AracGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SirketClient.AracService.AracResult arac;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int aracID;
        
        public AracGuncelleRequestBody() {
        }
        
        public AracGuncelleRequestBody(SirketClient.AracService.AracResult arac, int aracID) {
            this.arac = arac;
            this.aracID = aracID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AracGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AracGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public SirketClient.AracService.AracGuncelleResponseBody Body;
        
        public AracGuncelleResponse() {
        }
        
        public AracGuncelleResponse(SirketClient.AracService.AracGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AracGuncelleResponseBody {
        
        public AracGuncelleResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AracServiceSoapChannel : SirketClient.AracService.AracServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracServiceSoapClient : System.ServiceModel.ClientBase<SirketClient.AracService.AracServiceSoap>, SirketClient.AracService.AracServiceSoap {
        
        public AracServiceSoapClient() {
        }
        
        public AracServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.AracService.YeniAracEkleResponse SirketClient.AracService.AracServiceSoap.YeniAracEkle(SirketClient.AracService.YeniAracEkleRequest request) {
            return base.Channel.YeniAracEkle(request);
        }
        
        public void YeniAracEkle(SirketClient.AracService.AracResult arac, string KullaniciAdi) {
            SirketClient.AracService.YeniAracEkleRequest inValue = new SirketClient.AracService.YeniAracEkleRequest();
            inValue.Body = new SirketClient.AracService.YeniAracEkleRequestBody();
            inValue.Body.arac = arac;
            inValue.Body.KullaniciAdi = KullaniciAdi;
            SirketClient.AracService.YeniAracEkleResponse retVal = ((SirketClient.AracService.AracServiceSoap)(this)).YeniAracEkle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.AracService.YeniAracEkleResponse> SirketClient.AracService.AracServiceSoap.YeniAracEkleAsync(SirketClient.AracService.YeniAracEkleRequest request) {
            return base.Channel.YeniAracEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.AracService.YeniAracEkleResponse> YeniAracEkleAsync(SirketClient.AracService.AracResult arac, string KullaniciAdi) {
            SirketClient.AracService.YeniAracEkleRequest inValue = new SirketClient.AracService.YeniAracEkleRequest();
            inValue.Body = new SirketClient.AracService.YeniAracEkleRequestBody();
            inValue.Body.arac = arac;
            inValue.Body.KullaniciAdi = KullaniciAdi;
            return ((SirketClient.AracService.AracServiceSoap)(this)).YeniAracEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.AracService.AracListeleResponse SirketClient.AracService.AracServiceSoap.AracListele(SirketClient.AracService.AracListeleRequest request) {
            return base.Channel.AracListele(request);
        }
        
        public System.Collections.Generic.List<SirketClient.AracService.AracResult> AracListele(string KullaniciAdi) {
            SirketClient.AracService.AracListeleRequest inValue = new SirketClient.AracService.AracListeleRequest();
            inValue.Body = new SirketClient.AracService.AracListeleRequestBody();
            inValue.Body.KullaniciAdi = KullaniciAdi;
            SirketClient.AracService.AracListeleResponse retVal = ((SirketClient.AracService.AracServiceSoap)(this)).AracListele(inValue);
            return retVal.Body.AracListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.AracService.AracListeleResponse> SirketClient.AracService.AracServiceSoap.AracListeleAsync(SirketClient.AracService.AracListeleRequest request) {
            return base.Channel.AracListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.AracService.AracListeleResponse> AracListeleAsync(string KullaniciAdi) {
            SirketClient.AracService.AracListeleRequest inValue = new SirketClient.AracService.AracListeleRequest();
            inValue.Body = new SirketClient.AracService.AracListeleRequestBody();
            inValue.Body.KullaniciAdi = KullaniciAdi;
            return ((SirketClient.AracService.AracServiceSoap)(this)).AracListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SirketClient.AracService.AracGuncelleResponse SirketClient.AracService.AracServiceSoap.AracGuncelle(SirketClient.AracService.AracGuncelleRequest request) {
            return base.Channel.AracGuncelle(request);
        }
        
        public void AracGuncelle(SirketClient.AracService.AracResult arac, int aracID) {
            SirketClient.AracService.AracGuncelleRequest inValue = new SirketClient.AracService.AracGuncelleRequest();
            inValue.Body = new SirketClient.AracService.AracGuncelleRequestBody();
            inValue.Body.arac = arac;
            inValue.Body.aracID = aracID;
            SirketClient.AracService.AracGuncelleResponse retVal = ((SirketClient.AracService.AracServiceSoap)(this)).AracGuncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SirketClient.AracService.AracGuncelleResponse> SirketClient.AracService.AracServiceSoap.AracGuncelleAsync(SirketClient.AracService.AracGuncelleRequest request) {
            return base.Channel.AracGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<SirketClient.AracService.AracGuncelleResponse> AracGuncelleAsync(SirketClient.AracService.AracResult arac, int aracID) {
            SirketClient.AracService.AracGuncelleRequest inValue = new SirketClient.AracService.AracGuncelleRequest();
            inValue.Body = new SirketClient.AracService.AracGuncelleRequestBody();
            inValue.Body.arac = arac;
            inValue.Body.aracID = aracID;
            return ((SirketClient.AracService.AracServiceSoap)(this)).AracGuncelleAsync(inValue);
        }
        
        public void AracSil(int aracID) {
            base.Channel.AracSil(aracID);
        }
        
        public System.Threading.Tasks.Task AracSilAsync(int aracID) {
            return base.Channel.AracSilAsync(aracID);
        }
    }
}
